wifi_ssid: "your ssid"
wifi_password: "your password"
mqtt_broker: "your mqtt broker address"
hass_api_password: "your hass api password" # hass will ask for it when adding the device
ota_password: "your ota_password"
